import { char, date, datetime, double, int, json, mysqlTable, primaryKey, text, tinyint, uniqueIndex, varchar } from 'drizzle-orm/mysql-core'

// Drizzle schema 用于类型安全查询；特殊 CHECK、FULLTEXT 与补挂外键由手写迁移负责。
export const goals = mysqlTable('goal', {
  id: char('id', { length: 36 }).primaryKey(), title: varchar('title', { length: 50 }).notNull(), description: text('description'),
  period: varchar('period', { length: 16 }).notNull(), metricType: varchar('metric_type', { length: 16 }).notNull(), unit: varchar('unit', { length: 32 }),
  startValue: double('start_value'), targetValue: double('target_value'), status: varchar('status', { length: 16 }).notNull(), dueDate: datetime('due_date', { mode: 'string', fsp: 3 }),
  createdAt: datetime('created_at', { mode: 'string', fsp: 3 }).notNull(), updatedAt: datetime('updated_at', { mode: 'string', fsp: 3 }).notNull()
})
export const goalRecords = mysqlTable('goal_record', { id: char('id', { length: 36 }).primaryKey(), goalId: char('goal_id', { length: 36 }).notNull(), value: double('value').notNull(), note: text('note'), recordedAt: datetime('recorded_at', { mode: 'string', fsp: 3 }).notNull(), createdAt: datetime('created_at', { mode: 'string', fsp: 3 }).notNull() })
export const milestones = mysqlTable('milestone', { id: char('id', { length: 36 }).primaryKey(), goalId: char('goal_id', { length: 36 }).notNull(), title: varchar('title', { length: 100 }).notNull(), isDone: tinyint('is_done').notNull(), doneAt: datetime('done_at', { mode: 'string', fsp: 3 }), sortOrder: int('sort_order').notNull(), createdAt: datetime('created_at', { mode: 'string', fsp: 3 }).notNull(), updatedAt: datetime('updated_at', { mode: 'string', fsp: 3 }).notNull() })
export const projects = mysqlTable('project', { id: char('id', { length: 36 }).primaryKey(), goalId: char('goal_id', { length: 36 }), title: varchar('title', { length: 50 }).notNull(), description: text('description'), status: varchar('status', { length: 16 }).notNull(), startAt: datetime('start_at', { mode: 'string', fsp: 3 }), endAt: datetime('end_at', { mode: 'string', fsp: 3 }), createdAt: datetime('created_at', { mode: 'string', fsp: 3 }).notNull(), updatedAt: datetime('updated_at', { mode: 'string', fsp: 3 }).notNull() })
export const tasks = mysqlTable('task', { id: char('id', { length: 36 }).primaryKey(), goalId: char('goal_id', { length: 36 }), projectId: char('project_id', { length: 36 }), title: varchar('title', { length: 100 }).notNull(), note: text('note'), dueDate: datetime('due_date', { mode: 'string', fsp: 3 }), status: varchar('status', { length: 16 }).notNull(), completedAt: datetime('completed_at', { mode: 'string', fsp: 3 }), createdAt: datetime('created_at', { mode: 'string', fsp: 3 }).notNull(), updatedAt: datetime('updated_at', { mode: 'string', fsp: 3 }).notNull() })
export const habits = mysqlTable('habit', { id: char('id', { length: 36 }).primaryKey(), name: varchar('name', { length: 50 }).notNull(), note: text('note'), frequencyType: varchar('frequency_type', { length: 20 }).notNull(), weeklyTarget: int('weekly_target'), streak: int('streak').notNull(), lastDoneOn: date('last_done_on', { mode: 'string' }), createdAt: datetime('created_at', { mode: 'string', fsp: 3 }).notNull(), updatedAt: datetime('updated_at', { mode: 'string', fsp: 3 }).notNull() })
export const habitCheckins = mysqlTable('habit_checkin', { id: char('id', { length: 36 }).primaryKey(), habitId: char('habit_id', { length: 36 }).notNull(), checkedOn: date('checked_on', { mode: 'string' }).notNull(), createdAt: datetime('created_at', { mode: 'string', fsp: 3 }).notNull() }, (table) => [uniqueIndex('uk_habit_checkin_habit_day').on(table.habitId, table.checkedOn)])
export const tags = mysqlTable('tag', { id: char('id', { length: 36 }).primaryKey(), name: varchar('name', { length: 100 }).notNull(), createdAt: datetime('created_at', { mode: 'string', fsp: 3 }).notNull() }, (table) => [uniqueIndex('uk_tag_name').on(table.name)])
export const entityTags = mysqlTable('entity_tag', { entityType: varchar('entity_type', { length: 32 }).notNull(), entityId: char('entity_id', { length: 36 }).notNull(), tagId: char('tag_id', { length: 36 }).notNull() }, (table) => [primaryKey({ columns: [table.entityType, table.entityId, table.tagId] })])
export const appSettings = mysqlTable('app_setting', { key: varchar('key', { length: 128 }).primaryKey(), valueJson: json('value_json').notNull(), updatedAt: datetime('updated_at', { mode: 'string', fsp: 3 }).notNull() })
